# Generated by Django 2.2.24 on 2022-02-26 09:03

from django.db import migrations


def fill_data_field(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        if flat.construction_year > 2014:
            flat.new_building = True
        else:
            flat.new_building = False


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(fill_data_field)
    ]
