# Generated by Django 2.2.24 on 2022-02-26 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20220226_1203'),
        ('property', '0005_auto_20220226_1216'),
    ]

    operations = [
    ]
