# Generated by Django 2.2.24 on 2022-02-26 09:19

from django.db import migrations


def fill_data_field(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        if flat.construction_year > 2014:
            flat.new_building = True
            flat.save()
        else:
            flat.new_building = False
            flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_merge_20220226_1217'),
    ]

    operations = [
        migrations.RunPython(fill_data_field)
    ]
