# Generated by Django 2.2.24 on 2022-02-28 10:30

from django.db import migrations


def load_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        Owner.objects.get_or_create(name=flat.owner_name,
                                    owners_phonenumber=flat.owners_phonenumber,
                                    owner_pure_phone=flat.owner_pure_phone,
                                    )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20220228_1326'),
    ]

    operations = [
        migrations.RunPython(load_owners)
    ]
