# Generated by Django 2.2.24 on 2022-02-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20220228_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='my_flats',
            field=models.ManyToManyField(to='property.Flat', verbose_name='Квартиры в собственности'),
        ),
    ]
