# Generated by Django 2.2.24 on 2022-03-17 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0018_auto_20220317_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='user',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='my_flats',
        ),
        migrations.AddField(
            model_name='claim',
            name='claim_owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Кто жаловался'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='owner',
            name='flats',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='flats', to='property.Flat', verbose_name='Квартиры в собственности'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flat', to='property.Flat', verbose_name='Квартира на которую пожаловались'),
        ),
    ]
